version: '3'
services:
  db:
    container_name: wagtail_db
    build:
      context: .
      dockerfile: Dockerfile.db
    env_file: .env
    image: mysql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:6033"
  cache:
    container_name: wagtail_cache
    image: redis
  server:
    restart: always
    container_name: wagtail_server
    entrypoint: /code/bootstrap.local.sh
    build: 
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./app:/code
    ports:
      - "${SERVER_PORT}:8000"
    depends_on: 
      - db
